#!/usr/bin/env bash

# This script is just here to run pylint checkers in a standard
# single-point-of-truth way. Feel free to run it manually instead.

set -e

ARGS=( "${@:-.}" )

# run from root of current project
cd "$(dirname "$(dirname "$(realpath "$0")")")" || exit 1

exec "dev/run-in-venv" run python -m pylint "${ARGS[@]}"
