#!/usr/bin/env sh

# This script is just here to run all checkers in a standard single-point-of-truth
# way. Feel free to run them instead.

set -e

echo "Run validity checkers.."

if git status 2>/dev/null; then
    git status
fi

# run from root of current project
cd "$(dirname "$(dirname "$(realpath "$0")")")"

exec "dev/run-in-venv" pre-commit run --hook-stage pre-commit --all-files
