#!/usr/bin/env sh

# This script is just here to run all checkers in a standard single-point-of-truth
# way. Feel free to run them instead.
# To be used in pre-commit-hook

set -e

echo "Run validity checkers.."

if git status 2>/dev/null; then
    git status
fi

# run from root of current project
cd "$(dirname "$(dirname "$(realpath "$0")")")"

dev/check-python-doctests "$@"
dev/check-python-format "$@"
dev/check-python-linting "$@"
#dev/check-python-typing $@
dev/check-yaml-linting "$@"
dev/check-shellscripts "$@"
