#!/usr/bin/env bash

# This script is just here to fix issues in a standard
# single-point-of-truth way. Feel free to run it manually instead.

set -e

if [ "$#" -gt 0 ]; then
    ARGS=(--files "$@")
else
    ARGS=(--all-files)
fi

# run from root of current project
cd "$(dirname "$(dirname "$(realpath "$0")")")" || exit 1

"dev/run-in-venv" pre-commit run fix-python-linting --hook-stage manual "${ARGS[@]}"
